#!/usr/bin/env bash
set -e
pip install torch==1.13.0+cu117 torchvision==0.14.0+cu117 torchaudio===0.13.0 -f https://download.pytorch.org/whl/cu117/torch_stable.html
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html